(function(){
'use strict';
const $=selector=>document.querySelector(selector),modal=$('#modal'),backdrop=$('#backdrop'),box=modal.querySelector('.box');
let step=1,format='',lectureData=null,sourceFile=null,generatedURL='';
const icons={web:'▣',file:'▤',map:'⌘'};
const enc=value=>btoa(Array.from(new TextEncoder().encode(JSON.stringify(value)),byte=>String.fromCharCode(byte)).join('')).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const dec=value=>JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(value.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-value.length%4)%4)),char=>char.charCodeAt(0))));
const option=(value,title,description,icon)=>`<button class="option" type="button" data-choice="${value}"><span class="icon" aria-hidden="true">${icon}</span><span><strong>${title}</strong><small>${description}</small></span><b class="arrow">→</b></button>`;
function shell(title,description,content){box.innerHTML=`<div class="wizard-top"><button class="x wizard-back" type="button" aria-label="Previous step" ${step===1?'hidden':''}>←</button><div class="wizard-progress" aria-label="Creation progress"><i class="done"></i><i class="${step>=2?'done':''}"></i></div><button class="x wizard-close" type="button" aria-label="Close dialog">×</button></div><div class="wizard-heading"><span>Step ${step} of 2</span><h2>${title}</h2><p>${description}</p></div>${content}`;box.querySelector('.wizard-close').onclick=hide;const back=box.querySelector('.wizard-back');if(back)back.onclick=()=>{step=Math.max(1,step-1);renderStep()}}
function renderStep(){
 if(step===1){shell('Choose the output.','Choose what the platform should generate.',`<div class="options">${option('web','Web app','Build an interactive browser-based lecture.',icons.web)}${option('lecture-file','Lecture file','Generate a portable lecture document.',icons.file)}${option('mind-map','Mind map','Generate a connected visual knowledge map.',icons.map)}</div>`);box.querySelector('.options').onclick=event=>{const choice=event.target.closest('[data-choice]');if(!choice)return;format=choice.dataset.choice;step=2;renderStep()}}
 else renderImportStep();
 const focusable=box.querySelector('.option,.wizard-back,input,button');focusable?.focus();
}
function renderImportStep(){
 if(format!=='web'){const name=format==='lecture-file'?'Lecture file':'Mind map';shell(name+' generator','The selection flow is ready; this generator is not connected to an output engine yet.',`<div class="workflow-message"><strong>${name} selected</strong><p>Return to step 1 and choose Web app to use the available generator.</p></div>`);return}
 renderGeneralImport();
}
function renderGeneralImport(){
 shell('Import lecture content.','Choose the lecture JSON. Add the original PDF, PPTX, or DOCX only when its image placeholders need extraction.',`<div class="import-links"><a href="medical-lecture.template.json?v=4.9.0" download>Blank template ↗</a><a href="lectures/carbohydrate-biochemistry.json?v=4.5.0" download>Carbohydrates ↗</a><a href="lectures/heart-drugs-pharmacology.json?v=4.5.0" download>Heart drugs ↗</a><a href="lectures/immunology-lecture-1-innate-immunity.json?v=4.7.0" download>Immunology 1 ↗</a><a href="lectures/immunology-lecture-2-cells-and-organs.json?v=4.7.0" download>Immunology 2 ↗</a><a href="lectures/immunology-lecture-3-antigens.json?v=4.7.0" download>Immunology 3 ↗</a><a href="step-processes.example.json?v=4.6.0" download>Process examples ↗</a></div><div class="import-choice"><span>A</span><div><strong>Import lecture web app template</strong><small>Required JSON controlling Study, Exam, processes, and image locations.</small></div></div><label class="drop" for="jsonFile"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M12 16V3m0 0L7 8m5-5 5 5M4 14v5a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5"/></svg><strong>Select lecture JSON</strong><small>The standardized template determines content order and interactions.</small><span class="pick">Choose JSON file</span></label><input id="jsonFile" type="file" accept=".json,.JSON,application/json,text/json,application/octet-stream" hidden><div class="file-name" id="fileName" aria-live="polite">No lecture JSON selected.</div><div class="import-choice"><span>B</span><div><strong>Import lecture file</strong><small>Optional unless the JSON contains image placeholders.</small></div></div><label class="drop source-drop" for="sourceFile"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M7 3h7l4 4v14H7zM14 3v5h5M10 13h5M10 17h5"/></svg><strong>Select PDF, PPTX, or DOCX</strong><small>The extractor resolves images at the locations declared by the JSON.</small><span class="pick">Choose lecture file</span></label><input id="sourceFile" type="file" accept=".pdf,.pptx,.docx,application/pdf,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/vnd.openxmlformats-officedocument.wordprocessingml.document" hidden><div class="file-name" id="sourceFileName" aria-live="polite">No source file selected.</div><button class="build" id="build" disabled>Build lecture web app</button>`);
 lectureData=null;sourceFile=null;const images=()=>lectureData?.blocks?.filter(block=>block?.type==='image')||[],refresh=()=>{$('#build').disabled=!lectureData||(images().length>0&&!sourceFile)};
 $('#jsonFile').onchange=async event=>{let parsed=null;const file=event.target.files[0];if(!file)return;try{if(file.size>250000)throw Error('Use a file smaller than 250 KB.');parsed=JSON.parse(await file.text());validateLecture(parsed);lectureData=parsed;const count=images().length;$('#fileName').textContent='Ready: '+file.name+' · '+lectureData.blocks.length+' blocks'+(count?' · '+count+' image placeholder'+(count===1?'':'s'):'');$('#sourceFileName').textContent=count?(sourceFile?'Source ready: '+sourceFile.name:'Select the source .'+images()[0].source.fileType+' file to resolve images.'):'No image placeholders; the source lecture file is optional.';refresh()}catch(error){lectureData=null;$('#fileName').textContent='Invalid lecture: '+error.message;refresh()}};
 $('#sourceFile').onchange=event=>{const file=event.target.files[0];if(!file)return;const type=(file.name.split('.').pop()||'').toLowerCase();if(!['pdf','pptx','docx'].includes(type)){sourceFile=null;$('#sourceFileName').textContent='Unsupported source file. Choose PDF, PPTX, or DOCX.'}else if(file.size>50*1024*1024){sourceFile=null;$('#sourceFileName').textContent='Use a source file smaller than 50 MB.'}else{sourceFile=file;$('#sourceFileName').textContent='Source ready: '+file.name}refresh()};
 $('#build').onclick=async()=>{if(!lectureData)return;const button=$('#build'),original=button.textContent;button.disabled=true;button.textContent=images().length?'Extracting images…':'Building…';try{const output=await resolveLectureImages(lectureData,sourceFile,message=>{$('#sourceFileName').textContent=message});validateLecture(output);generatedURL=location.href.split('#')[0].split('?')[0]+'#lecture='+enc(output);if(generatedURL.length>1800000)throw Error('The generated link is too large for reliable sharing. Use fewer images or tighter crops.');renderResult('Lecture web app','A two-page Study and Exam app was built from the selected JSON and extracted images.')}catch(error){$('#sourceFileName').textContent='Could not build lecture: '+error.message}finally{button.textContent=original;refresh()}};
}
function renderResult(title,description){step=2;shell(title+' ready.',description,`<div class="link" id="link"></div><div class="actions"><button class="open" id="open" type="button">Open web app ↗</button><button class="copy" id="copy" type="button">Copy link</button></div><div class="notice" id="notice" aria-live="polite"></div>`);$('#link').textContent=generatedURL;$('#open').onclick=()=>window.open(generatedURL,'_blank','noopener');$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(generatedURL);$('#notice').textContent='Link copied to your clipboard.'}catch{$('#notice').textContent='Select the link above and copy it manually.'}};$('#open').focus()}
function reset(){step=1;format='';lectureData=null;sourceFile=null;generatedURL='';renderStep()}
function hide(){modal.classList.remove('show');backdrop.classList.remove('show');modal.inert=true;modal.setAttribute('aria-hidden','true');document.body.style.overflow='';document.querySelector('body>main').inert=false;$('#start')?.focus()}
function show(){reset();modal.inert=false;modal.removeAttribute('aria-hidden');modal.classList.add('show');backdrop.classList.add('show');document.body.style.overflow='hidden';document.querySelector('body>main').inert=true;box.querySelector('.option')?.focus()}
modal.inert=true;modal.setAttribute('aria-hidden','true');modal.setAttribute('aria-label','Create a learning resource');modal.addEventListener('keydown',event=>{if(event.key!=='Tab')return;const nodes=[...modal.querySelectorAll('button,input,a')].filter(item=>!item.disabled&&item.getClientRects().length);const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&modal.classList.contains('show'))hide()});$('#start').onclick=show;backdrop.onclick=hide;
renderStep();
if(location.hash.startsWith('#lecture=')){try{renderLecture(dec(location.hash.slice(9)))}catch{document.body.textContent='This lecture link is invalid or incomplete.'}}else if(location.hash.startsWith('#workspace/')){document.head.innerHTML='<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Untitled web app</title>';document.body.innerHTML='<div class="workspace"><div>Untitled web app</div></div>'}
})();
