(function(){
'use strict';
const SVG='http://www.w3.org/2000/svg',types=new Set(['text','strong','waypoint']);
const fail=(ok,message)=>{if(!ok)throw Error(message)},finite=(value,path)=>fail(typeof value==='number'&&Number.isFinite(value),path+' must be a finite number');
function validateHistologyLecture(data){
 fail(data&&typeof data==='object'&&!Array.isArray(data),'The histology JSON root must be an object.');
 fail(data.schema_version===1,'schema_version must equal 1.');
 fail(data.metadata&&typeof data.metadata==='object','metadata is required.');
 for(const key of ['id','title','subject','description'])fail(typeof data.metadata[key]==='string'&&data.metadata[key].trim(),'metadata.'+key+' is required.');
 fail(data.viewer&&typeof data.viewer==='object','viewer is required.');
 fail(typeof data.viewer.dzi_url==='string'&&/^https?:\/\//i.test(data.viewer.dzi_url),'viewer.dzi_url must be an HTTP(S) URL.');
 fail(data.viewer.coordinate_space==='image-pixels','viewer.coordinate_space must be image-pixels.');
 finite(data.viewer.image_width,'viewer.image_width');finite(data.viewer.image_height,'viewer.image_height');
 fail(data.viewer.image_width>0&&data.viewer.image_height>0,'Slide dimensions must be positive.');
 fail(Array.isArray(data.sections)&&data.sections.length,'sections must be a non-empty array.');
 const ids=new Set();
 data.sections.forEach((section,si)=>{
  fail(section&&typeof section.id==='string'&&section.id,'sections['+si+'].id is required.');fail(!ids.has(section.id),'Duplicate id: '+section.id);ids.add(section.id);
  fail(typeof section.title==='string'&&section.title,'sections['+si+'].title is required.');fail(Array.isArray(section.blocks)&&section.blocks.length,'sections['+si+'].blocks must not be empty.');
  section.blocks.forEach((block,bi)=>{fail(block.type==='paragraph','Only paragraph blocks are supported.');fail(Array.isArray(block.nodes)&&block.nodes.length,'Paragraph nodes must not be empty.');block.nodes.forEach((node,ni)=>{const path='sections['+si+'].blocks['+bi+'].nodes['+ni+']';fail(types.has(node.type),path+'.type is unsupported.');fail(typeof node.text==='string'&&node.text,path+'.text is required.');if(node.type==='waypoint'){fail(typeof node.id==='string'&&node.id,path+'.id is required.');fail(!ids.has(node.id),'Duplicate id: '+node.id);ids.add(node.id);for(const key of ['x','y','zoom_level'])finite(node[key],path+'.'+key);fail(node.x>=0&&node.x<=data.viewer.image_width&&node.y>=0&&node.y<=data.viewer.image_height,path+' lies outside the slide.');fail(node.zoom_level>0,path+'.zoom_level must be positive.')}})});
 });
 const overlayIds=new Set();(data.overlays||[]).forEach((group,gi)=>{const path='overlays['+gi+']';fail(group&&typeof group.id==='string'&&group.id,path+'.id is required.');fail(!overlayIds.has(group.id),'Duplicate overlay id: '+group.id);overlayIds.add(group.id);fail(typeof group.label==='string'&&group.label,path+'.label is required.');fail(/^#[0-9a-f]{6}$/i.test(group.color),path+'.color must be a six-digit hex value.');fail(Array.isArray(group.shapes)&&group.shapes.length,path+'.shapes must not be empty.');group.shapes.forEach((shape,i)=>{const p=path+'.shapes['+i+']';fail(['rectangle','polygon'].includes(shape.type),p+'.type is unsupported.');fail(typeof shape.label==='string'&&shape.label,p+'.label is required.');if(shape.type==='rectangle'){for(const key of ['x','y','width','height'])finite(shape[key],p+'.'+key);fail(shape.width>0&&shape.height>0,p+' dimensions must be positive.')}else{fail(Array.isArray(shape.points)&&shape.points.length>=3,p+'.points requires at least three points.');shape.points.forEach((point,j)=>{finite(point.x,p+'.points['+j+'].x');finite(point.y,p+'.points['+j+'].y')})}})});
 return data;
}
function node(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!=null)e.textContent=text;return e}
function renderHistologyLecture(input){
 const data=validateHistologyLecture(input);document.title=data.metadata.title+' · '+data.metadata.subject;document.body.className='histology-page';document.body.innerHTML='';
 const root=node('main','histo-root'),content=node('section','histo-content'),viewerPane=node('aside','histo-viewer-pane'),head=node('header','histo-head'),copy=node('div','histo-head-copy'),subject=node('p','histo-subject',data.metadata.subject),title=node('h1','',data.metadata.title),mobileOpen=node('button','histo-mobile-open','Explore slide');mobileOpen.type='button';copy.append(subject,title);head.append(copy,mobileOpen);content.append(head);
 const body=node('div','histo-copy'),intro=node('div','histo-intro'),introTag=node('span','', 'Whole-slide interactive lecture'),introText=node('p','',data.metadata.description);intro.append(introTag,introText);body.append(intro);
 const waypointButtons=[];data.sections.forEach((section,index)=>{const s=node('section','histo-section');s.id=section.id;s.append(node('span','histo-section-number','Section '+String(index+1).padStart(2,'0')),node('h2','',section.title));section.blocks.forEach(block=>{const p=node('p','');block.nodes.forEach(item=>{if(item.type==='waypoint'){const b=node('button','histo-waypoint',item.text);b.type='button';b.dataset.waypoint=item.id;b.setAttribute('aria-label','View '+item.text+' on the slide');b.addEventListener('click',()=>focusWaypoint(b,item));waypointButtons.push(b);p.append(b)}else{const span=node(item.type==='strong'?'strong':'span','',item.text);p.append(span)}});s.append(p)});body.append(s)});content.append(body);
 const viewerHead=node('div','histo-viewer-head'),viewerName=node('div',''),viewerKicker=node('span','', 'Live specimen'),viewerLabel=node('strong','',data.viewer.label||data.metadata.title),status=node('span','histo-status','Loading slide…'),close=node('button','histo-close','×');close.type='button';close.setAttribute('aria-label','Close slide viewer');viewerName.append(viewerKicker,viewerLabel);viewerHead.append(viewerName,status,close);
 const stage=node('div','histo-stage'),viewer=node('div','histo-viewer');viewer.id='histo-osd';viewer.tabIndex=0;const error=node('div','histo-error');error.hidden=true;const controls=node('div','histo-controls');stage.append(viewer,error,controls);const overlayBar=node('div','histo-overlays');viewerPane.append(viewerHead,stage,overlayBar);root.append(content,viewerPane);document.body.append(root);
 mobileOpen.onclick=()=>document.body.classList.add('histo-viewer-open');close.onclick=()=>document.body.classList.remove('histo-viewer-open');
 let osd=null,tiled=null,pending=null,active=null;const overlayElements=new Map();
 function showError(message){error.hidden=false;error.textContent=message;status.textContent='Slide unavailable'}
 function focusWaypoint(button,waypoint){document.body.classList.add('histo-viewer-open');if(active)active.removeAttribute('aria-current');active=button;button.setAttribute('aria-current','true');if(!tiled){pending={button,waypoint};return}const point=tiled.imageToViewportCoordinates(waypoint.x,waypoint.y),zoom=tiled.imageToViewportZoom(waypoint.zoom_level);osd.viewport.panTo(point,false);osd.viewport.zoomTo(zoom,point,false);osd.viewport.applyConstraints(false)}
 function control(label,text,handler){const b=node('button','',text);b.type='button';b.setAttribute('aria-label',label);b.onclick=handler;controls.append(b)}
 if(!window.OpenSeadragon){showError('OpenSeadragon could not be loaded. Check the network connection.');return}
 osd=OpenSeadragon({element:viewer,tileSources:data.viewer.dzi_url,showNavigator:data.viewer.show_navigator!==false,navigatorPosition:'BOTTOM_RIGHT',navigatorAutoFade:false,showNavigationControl:false,animationTime:.75,blendTime:.15,constrainDuringPan:true,visibilityRatio:.5,minZoomImageRatio:.75,maxZoomPixelRatio:data.viewer.max_zoom_pixel_ratio||4,crossOriginPolicy:'Anonymous',ajaxWithCredentials:false});
 control('Zoom in','+',()=>{osd.viewport.zoomBy(1.5);osd.viewport.applyConstraints()});control('Zoom out','−',()=>{osd.viewport.zoomBy(1/1.5);osd.viewport.applyConstraints()});control('Reset slide view','⌂',()=>osd.viewport.goHome());control('Toggle full screen','⛶',()=>document.fullscreenElement?document.exitFullscreen():viewerPane.requestFullscreen());
 osd.addHandler('open',()=>{tiled=osd.world.getItemAt(0);status.textContent='Slide ready';renderOverlays();if(pending){const next=pending;pending=null;focusWaypoint(next.button,next.waypoint)}});osd.addHandler('open-failed',event=>showError(event.message||'The DZI slide could not be opened.'));
 function shapeElement(shape,color){const g=document.createElementNS(SVG,'g'),mark=document.createElementNS(SVG,shape.type==='rectangle'?'rect':'polygon');let x,y;if(shape.type==='rectangle'){for(const key of ['x','y','width','height'])mark.setAttribute(key,shape[key]);x=shape.x;y=shape.y}else{mark.setAttribute('points',shape.points.map(p=>p.x+','+p.y).join(' '));x=Math.min(...shape.points.map(p=>p.x));y=Math.min(...shape.points.map(p=>p.y))}mark.setAttribute('fill',color);mark.setAttribute('fill-opacity','.12');mark.setAttribute('stroke',color);mark.setAttribute('stroke-width','2');mark.setAttribute('vector-effect','non-scaling-stroke');const label=document.createElementNS(SVG,'text');label.setAttribute('x',x);label.setAttribute('y',Math.max(1000,y-300));label.setAttribute('fill','#fff');label.setAttribute('font-size','1000');label.setAttribute('font-weight','700');label.setAttribute('stroke','#0f172a');label.setAttribute('stroke-width','180');label.setAttribute('paint-order','stroke');label.textContent=shape.label;const tip=document.createElementNS(SVG,'title');tip.textContent=shape.label;g.append(tip,mark,label);return g}
 function renderOverlays(){osd.clearOverlays();overlayElements.clear();const bounds=tiled.imageToViewportRectangle(0,0,data.viewer.image_width,data.viewer.image_height);(data.overlays||[]).forEach(group=>{const svg=document.createElementNS(SVG,'svg');svg.setAttribute('viewBox','0 0 '+data.viewer.image_width+' '+data.viewer.image_height);svg.setAttribute('preserveAspectRatio','none');svg.style.pointerEvents='none';group.shapes.forEach(shape=>svg.append(shapeElement(shape,group.color)));osd.addOverlay({element:svg,location:bounds,checkResize:false});overlayElements.set(group.id,svg);svg.style.display=group.visible_by_default===false?'none':''})}
 if((data.overlays||[]).length){overlayBar.append(node('span','','Diagnostic overlays'));data.overlays.forEach(group=>{const label=node('label',''),input=document.createElement('input'),dot=node('i',''),text=node('b','',group.label);input.type='checkbox';input.checked=group.visible_by_default!==false;dot.style.background=group.color;input.onchange=()=>{const e=overlayElements.get(group.id);if(e)e.style.display=input.checked?'':'none'};label.append(input,dot,text);overlayBar.append(label)})}else overlayBar.hidden=true;
}
window.validateHistologyLecture=validateHistologyLecture;window.renderHistologyLecture=renderHistologyLecture;
})();
