/* Verdant lecture reader. All imported strings are rendered as text, never HTML. */
(() => {
'use strict';
const types=new Set(['title','subtitle','paragraph','note','callout','flow','table','question','checklist','objectives','section','references','step-process','tracked-step-process']);
const str=(x,name,required=false)=>{if((required&&(!x||typeof x!=='string'))||(x!=null&&typeof x!=='string'))throw Error(name+' must be text.');};
window.validateLecture=d=>{
 if(!d||typeof d!=='object'||Array.isArray(d))throw Error('Lecture must be an object.');
 str(d.title,'title',true);if(!Array.isArray(d.blocks)||!d.blocks.length||d.blocks.length>200)throw Error('Use between 1 and 200 blocks.');
 for(const k of ['subtitle','course','id','author','level'])str(d[k],k);
 if(d.schemaVersion!=null&&![2,3,4].includes(d.schemaVersion))throw Error('Unsupported schemaVersion. Use 4, 3, 2, or omit it for legacy files.');
 if(d.durationMinutes!=null&&(!Number.isFinite(d.durationMinutes)||d.durationMinutes<=0))throw Error('durationMinutes must be positive.');
 for(const [i,b] of d.blocks.entries()){
 if(!b||!types.has(b.type))throw Error('Block '+(i+1)+': unknown type.');
 for(const k of ['id','heading','title','label','text','prompt','answer','description','variant'])str(b[k],'Block '+(i+1)+' '+k);
 if(['title','subtitle','paragraph','note','callout'].includes(b.type))str(b.text,'Block '+(i+1)+' text',true);
 if(b.type==='step-process'||b.type==='tracked-step-process')validateStepProcess(b);
 if(b.type==='section')str(b.title,'section title',true);
 if(['checklist','objectives','references'].includes(b.type)&&(!Array.isArray(b.items)||b.items.some(x=>typeof x!=='string')))throw Error(b.type+' items must be text arrays.');
 if(b.type==='flow'&&(!Array.isArray(b.steps)||!b.steps.length||b.steps.some(x=>typeof x!=='string'&&(!x||typeof x.title!=='string'||(x.description!=null&&typeof x.description!=='string')))))throw Error('Flow steps need text or title/description objects.');
 if(b.type==='table'&&(!Array.isArray(b.columns)||!b.columns.length||b.columns.some(x=>typeof x!=='string')||!Array.isArray(b.rows)||b.rows.some(row=>!Array.isArray(row)||row.length!==b.columns.length||row.some(x=>typeof x!=='string'))))throw Error('Table rows must match the text columns.');
 if(b.type==='question'){str(b.prompt,'question prompt',true);str(b.answer,'question answer',true);if(b.options!=null&&(!Array.isArray(b.options)||b.options.length<2||b.options.some(x=>typeof x!=='string')||!Number.isInteger(b.correctIndex)||b.correctIndex<0||b.correctIndex>=b.options.length))throw Error('Question options require a valid correctIndex.');}
 }
 return d;
};
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;};
const button=(text,cls,fn)=>{const n=el('button',cls,text);n.type='button';n.onclick=fn;return n;};
function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
window.renderLecture=d=>{
 validateLecture(d);document.title=d.title+' · Verdant';document.body.replaceChildren();
 const root=el('div','lecture'),key='verdant:'+hash(JSON.stringify(d));let state={};
 try{state=JSON.parse(localStorage.getItem(key)||'{}')||{}}catch{}
 if(typeof state!=='object'||Array.isArray(state))state={};
 const save=()=>{try{localStorage.setItem(key,JSON.stringify(state));return true}catch{return false}};
 const top=el('nav','topbar');top.setAttribute('aria-label','Reader controls');const brand=el('a','wordmark','Verdant');brand.href=location.href.split('#')[0];brand.prepend(el('span','logo','✦'));
 const tools=el('div','toolbar');const theme=button('Dark mode','tool',()=>{const dark=root.classList.toggle('dark');theme.setAttribute('aria-pressed',dark);theme.textContent=dark?'Light mode':'Dark mode';state.dark=dark;save()});theme.setAttribute('aria-pressed',!!state.dark);if(state.dark){root.classList.add('dark');theme.textContent='Light mode'}
 const focus=button('Focus','tool',()=>{const on=root.classList.toggle('focus');focus.setAttribute('aria-pressed',on);focus.textContent=on?'Exit focus':'Focus'});focus.setAttribute('aria-pressed','false');tools.append(focus,theme,button('Print','tool',()=>window.print()));const line=el('div','progress-line');top.append(brand,el('span','top-label','The lecture collection'),tools,line);
 const reader=el('div','reader'),side=el('aside','sidebar'),toc=el('nav','toc');toc.setAttribute('aria-label','Lecture chapters');side.append(el('div','overline','Your learning space'),el('div','side-course',d.course||'Lecture notes'),toc);
 const meter=el('div','study-meter'),row=el('div','meter-row'),percent=el('span','','0%');row.append(el('span','','Reading progress'),percent);const track=el('div','track'),fill=el('i');track.append(fill);meter.append(row,track,el('div','overline','Read. Connect. Remember.'));const template=el('a','download','Download JSON template ↗');template.href='medical-lecture.template.json?v=4.1.0';template.download='medical-lecture.template.json';meter.append(template);side.append(meter);
 const article=el('main','article');article.id='lecture-content';const hero=el('header','lecture-hero reveal-in');hero.append(el('div','overline',(d.course||'LECTURE')+' / '+(d.level||'Study guide')),el('h1','',d.title),el('p','dek',d.subtitle||'A focused space to understand, connect, and remember.'));
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 280 280');svg.classList.add('hero-art');svg.setAttribute('aria-hidden','true');for(let i=0;i<8;i++){const c=document.createElementNS(svg.namespaceURI,'circle');c.setAttribute('cx',140+Math.sin(i)*22);c.setAttribute('cy',140+Math.cos(i)*22);c.setAttribute('r',40+i*12);svg.append(c)}hero.append(svg);
 const meta=el('div','hero-meta');for(const text of [d.author||'Verdant collection',(d.durationMinutes||Math.max(3,Math.ceil(JSON.stringify(d).length/1200)))+' min read',d.blocks.filter(b=>b.type==='question').length+' recall prompts'])meta.append(el('span','',text));hero.append(meta);article.append(hero);
 const intro=el('div','intro-strip');intro.append(el('span','','A little structure. A deeper understanding.'),button('Begin lecture ↓','primary',()=>chapters[0]?.scrollIntoView({behavior:motion()})));article.append(intro);
 const chapters=[],links=[];let section=null;const motion=()=>matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
 const newChapter=title=>{const index=chapters.length,s=el('section','chapter');s.id='chapter-'+(index+1);const h=el('div','chapter-heading'),group=el('div');group.append(el('span','chapter-number','CHAPTER '+String(index+1).padStart(2,'0')),el('h2','',title));const saved=!!state['bookmark'+index];const mark=button(saved?'★':'☆','bookmark',()=>{state['bookmark'+index]=!state['bookmark'+index];mark.textContent=state['bookmark'+index]?'★':'☆';mark.setAttribute('aria-pressed',!!state['bookmark'+index]);save()});mark.setAttribute('aria-label','Bookmark '+title);mark.setAttribute('aria-pressed',saved);h.append(group,mark);s.append(h);article.append(s);chapters.push(s);const a=el('a');a.href='#'+s.id;a.append(el('span','toc-num',String(index+1).padStart(2,'0')),el('span','',title));a.onclick=e=>{e.preventDefault();s.scrollIntoView({behavior:motion()})};toc.append(a);links.push(a);return s;};
 for(const [index,b] of d.blocks.entries()){
 if(b.type==='section'||b.type==='title'){section=newChapter(b.title||b.text);if(b.description)section.append(el('p','',b.description));continue}
 if(!section)section=newChapter('The essentials');const block=el('div','block '+b.type+(b.variant==='lead'?' lead':''));
 if(b.type==='paragraph'||b.type==='subtitle'){if(b.heading)block.append(el('h3','',b.heading));block.append(el('p','',b.text))}
 if(['note','callout'].includes(b.type)){block.append(el('span','note-icon',b.type==='note'?'↗':'✦'));const text=el('div');text.append(el('div','label',b.label||b.title||'Key point'),el('p','',b.text));block.append(text)}
 if(b.type==='objectives'||b.type==='references'){block.append(el('div','overline',b.title|| (b.type==='objectives'?'By the end of this lecture':'References')));const list=el('ul');for(const item of b.items)list.append(el('li','',item));block.append(list)}
 if(b.type==='flow'){block.classList.add('process');block.append(el('div','overline','Explore the sequence'),el('h3','',b.title||'Process'));const tabs=el('div','process-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label',b.title||'Process');const detail=el('div','step-detail');detail.id='process-'+index;detail.setAttribute('role','tabpanel');const items=b.steps.map(x=>typeof x==='string'?{title:x,description:''}:x),buttons=[];const select=i=>{buttons.forEach((btn,j)=>{btn.setAttribute('aria-selected',i===j);btn.tabIndex=i===j?0:-1});detail.setAttribute('aria-labelledby','step-'+index+'-'+i);detail.replaceChildren(el('strong','',items[i].title),el('p','',items[i].description||'Step '+(i+1)+' of '+items.length+' in this sequence.'))};items.forEach((x,i)=>{const btn=button(x.title,'',()=>select(i));btn.prepend(el('span','step-number',String(i+1).padStart(2,'0')));btn.id='step-'+index+'-'+i;btn.setAttribute('role','tab');btn.setAttribute('aria-controls',detail.id);btn.onkeydown=e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%items.length;else if(e.key==='ArrowLeft')n=(i-1+items.length)%items.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=items.length-1;else return;e.preventDefault();select(n);buttons[n].focus()};buttons.push(btn);tabs.append(btn)});block.append(tabs,detail);select(0)}
 if(b.type==='table'){if(b.title)block.append(el('h3','',b.title));const wrap=el('div','table-wrap'),table=el('table'),caption=el('caption','','');caption.textContent=b.title||'Reference table';caption.hidden=true;table.append(caption);const head=el('thead'),hr=el('tr');b.columns.forEach(x=>{const th=el('th','',x);th.scope='col';hr.append(th)});head.append(hr);const body=el('tbody');b.rows.forEach(row=>{const tr=el('tr');row.forEach(x=>tr.append(el('td','',x)));body.append(tr)});table.append(head,body);wrap.append(table);block.append(wrap)}
 if(b.type==='question'){block.append(el('div','overline','Active recall / '+String(index+1).padStart(2,'0')),el('h3','',b.prompt));const answer=el('div','answer-panel');answer.id='answer-'+index;answer.hidden=true;answer.setAttribute('aria-live','polite');answer.textContent=b.answer;if(b.options){const options=el('div','quiz-options');b.options.forEach((text,i)=>{const btn=button(String.fromCharCode(65+i)+'  '+text,'quiz-option',()=>{options.querySelectorAll('button').forEach((n,j)=>{n.disabled=true;if(j===b.correctIndex)n.classList.add('correct')});if(i!==b.correctIndex)btn.classList.add('wrong');answer.textContent=(i===b.correctIndex?'Correct. ':'Review this concept. ')+b.answer;answer.hidden=false});options.append(btn)});block.append(options)}else{const reveal=button('Reveal explanation ↓','reveal',()=>{answer.hidden=!answer.hidden;reveal.setAttribute('aria-expanded',!answer.hidden);reveal.textContent=answer.hidden?'Reveal explanation ↓':'Hide explanation ↑'});reveal.setAttribute('aria-expanded','false');reveal.setAttribute('aria-controls',answer.id);block.append(reveal)}block.append(answer)}
 if(b.type==='checklist'){block.append(el('h3','',b.title||'Check your understanding'));const ul=el('ul');b.items.forEach((text,i)=>{const li=el('li'),label=el('label'),input=el('input');input.type='checkbox';input.checked=!!state['check'+index+'-'+i];input.onchange=()=>{state['check'+index+'-'+i]=input.checked;save()};label.append(input,el('span','',text));li.append(label);ul.append(li)});block.append(ul)}
 if(b.type==='step-process'||b.type==='tracked-step-process')block.append(renderStepProcess(b,'step-process-'+index));
 section.append(block);
 }
 const notes=el('section','block notes'),label=el('label','','Your margin notes'),area=el('textarea');area.id='lecture-notes';label.htmlFor=area.id;area.placeholder='What clicked? What would you like to revisit?';area.value=typeof state.notes==='string'?state.notes:'';const status=el('span','save-status','Notes stay in this browser.');status.setAttribute('aria-live','polite');area.oninput=()=>{state.notes=area.value;status.textContent=save()?'Saved in this browser.':'Storage unavailable. Copy your notes before leaving.'};notes.append(label,area,status);article.append(notes);
 const finish=el('div','finish'),message=el('div');message.append(el('div','overline','One idea at a time'),el('h3','','Make it stick.'),el('p','','Revisit the recall prompts. Explain the sequence in your own words.'));finish.append(message,button('Back to the beginning ↑','primary',()=>window.scrollTo({top:0,behavior:motion()})));article.append(finish);const footer=el('footer');footer.append(el('span','','VERDANT / LECTURE COLLECTION'),el('span','','Designed for deeper understanding'));article.append(footer);reader.append(side,article);const skip=el('a','skip-link','Skip to lecture');skip.href='#lecture-content';article.tabIndex=-1;root.append(skip,top,reader);document.body.append(root);
 const progress=()=>{const available=document.documentElement.scrollHeight-innerHeight;const p=available>0?Math.min(100,Math.max(0,Math.round(scrollY/available*100))):100;line.style.width=fill.style.width=p+'%';percent.textContent=p+'%';let current=0;chapters.forEach((s,i)=>{if(s.getBoundingClientRect().top<180)current=i});links.forEach((a,i)=>{a.classList.toggle('active',i===current);if(i===current)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})};let scheduled=false;window.addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(()=>{progress();scheduled=false})}},{passive:true});window.addEventListener('resize',progress);progress();
};
})();
