/* Verdant lecture reader. All imported strings are rendered as text, never HTML. */
(() => {
'use strict';
const types=new Set(['title','subtitle','paragraph','note','callout','flow','table','list','question','checklist','objectives','section','references','step-process','tracked-step-process','structure-layers','substance-journey','image']);
const str=(x,name,required=false)=>{if((required&&(!x||typeof x!=='string'))||(x!=null&&typeof x!=='string'))throw Error(name+' must be text.');};
const validateListItems=(items,name,depth=0)=>{
 if(!Array.isArray(items)||!items.length)throw Error(name+' needs at least one item.');
 if(depth>3)throw Error(name+' supports up to four levels.');
 items.forEach((item,index)=>{
  if(typeof item==='string'){if(!item.trim())throw Error(name+' item '+(index+1)+' must not be empty.');return}
  if(!item||typeof item!=='object'||Array.isArray(item))throw Error(name+' items must be text or nested item objects.');
  str(item.text,name+' item '+(index+1)+' text',true);str(item.label,name+' item '+(index+1)+' label');
  if(item.children!=null)validateListItems(item.children,name+' item '+(index+1)+' children',depth+1);
 });
};
window.validateLecture=d=>{
 if(!d||typeof d!=='object'||Array.isArray(d))throw Error('Lecture must be an object.');
 str(d.title,'title',true);if(!Array.isArray(d.blocks)||!d.blocks.length||d.blocks.length>200)throw Error('Use between 1 and 200 blocks.');
 for(const k of ['subtitle','course','id','author','level'])str(d[k],k);
 if(d.schemaVersion!=null&&![2,3,4].includes(d.schemaVersion))throw Error('Unsupported schemaVersion. Use 4, 3, 2, or omit it for legacy files.');
 if(d.durationMinutes!=null&&(!Number.isFinite(d.durationMinutes)||d.durationMinutes<=0))throw Error('durationMinutes must be positive.');
 if(d.exam!=null)validateExam(d.exam);
 for(const [i,b] of d.blocks.entries()){
 if(!b||!types.has(b.type))throw Error('Block '+(i+1)+': unknown type.');
 for(const k of ['id','heading','title','label','text','prompt','answer','description','variant'])str(b[k],'Block '+(i+1)+' '+k);
 if(['title','subtitle','paragraph','note','callout'].includes(b.type))str(b.text,'Block '+(i+1)+' text',true);
 if(b.type==='step-process'||b.type==='tracked-step-process')validateStepProcess(b);
 if(b.type==='structure-layers')validateStructureLayers(b);
 if(b.type==='substance-journey')validateSubstanceJourney(b);
 if(b.type==='section')str(b.title,'section title',true);
	 if(['checklist','objectives','references'].includes(b.type)&&(!Array.isArray(b.items)||b.items.some(x=>typeof x!=='string')))throw Error(b.type+' items must be text arrays.');
	 if(b.type==='list'){
	  str(b.title,'list title');str(b.description,'list description');
	  if(b.style!=null&&!['bullets','numbered','steps','key-points'].includes(b.style))throw Error('List style must be bullets, numbered, steps, or key-points.');
	  validateListItems(b.items,'List block '+(i+1));
	 }
	 if(b.type==='flow'&&(!Array.isArray(b.steps)||!b.steps.length||b.steps.some(x=>typeof x!=='string'&&(!x||typeof x.title!=='string'||(x.description!=null&&typeof x.description!=='string')))))throw Error('Flow steps need text or title/description objects.');
	 if(b.type==='table'){
	  str(b.purpose,'table purpose');str(b.description,'table description');
	  if(b.purpose!=null&&!['quick-comparison','simplify-complexity','rapid-review','structured-variables'].includes(b.purpose))throw Error('Table purpose must be quick-comparison, simplify-complexity, rapid-review, or structured-variables.');
	  if(!Array.isArray(b.columns)||b.columns.length<2||b.columns.some(x=>typeof x!=='string')||!Array.isArray(b.rows)||b.rows.some(row=>!Array.isArray(row)||row.length!==b.columns.length||row.some(x=>typeof x!=='string')))throw Error('Table rows must match at least two text columns.');
	 }
 if(b.type==='image'){
  str(b.processName,'image processName',true);str(b.alt,'image alt',true);for(const k of ['caption','sourceLabel','imageData'])str(b[k],'image '+k);
  const source=b.source;if(!source||!['pdf','pptx','docx'].includes(source.fileType))throw Error('Image block needs source.fileType set to pdf, pptx, or docx.');
  const positive=value=>Number.isInteger(value)&&value>0,media=typeof source.media==='string'&&source.media.trim();
  if(source.fileType==='pdf'&&!positive(source.page))throw Error('PDF image source needs a positive page number.');
  if(source.crop!=null&&(!Array.isArray(source.crop)||source.crop.length!==4||source.crop.some(value=>typeof value!=='number'||value<0||value>1)||source.crop[2]<=0||source.crop[3]<=0||source.crop[0]+source.crop[2]>1||source.crop[1]+source.crop[3]>1))throw Error('PDF crop must be [x, y, width, height] using values from 0 to 1.');
  if(source.fileType==='pptx'&&(!positive(source.slide)||(!positive(source.image)&&!media)))throw Error('PPTX image source needs a slide and an image number or media filename.');
  if(source.fileType==='docx'&&!positive(source.image)&&!media)throw Error('DOCX image source needs an image number or media filename.');
  if(b.imageData!=null&&(!/^data:image\/(?:png|jpeg|webp|gif|svg\+xml);base64,/i.test(b.imageData)||b.imageData.length>1600000))throw Error('imageData must be a supported base64 image below 1.6 MB.');
 }
 if(b.type==='question'){str(b.prompt,'question prompt',true);str(b.answer,'question answer',true);if(b.options!=null&&(!Array.isArray(b.options)||b.options.length<2||b.options.some(x=>typeof x!=='string')||!Number.isInteger(b.correctIndex)||b.correctIndex<0||b.correctIndex>=b.options.length))throw Error('Question options require a valid correctIndex.');}
 }
 return d;
};
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;};
const button=(text,cls,fn)=>{const n=el('button',cls,text);n.type='button';n.onclick=fn;return n;};
function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
window.renderLecture=d=>{
 validateLecture(d);document.body.classList.add('lecture-page');document.title=d.title+' · Verdant';document.body.replaceChildren();
 const root=el('div','lecture'),key='verdant:'+hash(JSON.stringify(d));let state={};
 try{state=JSON.parse(localStorage.getItem(key)||'{}')||{}}catch{}
 if(typeof state!=='object'||Array.isArray(state))state={};
 const save=()=>{try{localStorage.setItem(key,JSON.stringify(state));return true}catch{return false}};
 const top=el('nav','topbar');top.setAttribute('aria-label','Reader controls');const brand=el('a','wordmark','Verdant');brand.href=location.href.split('#')[0].split('?')[0];brand.prepend(el('span','logo','✦'));
 const pageNav=el('div','page-switch');pageNav.setAttribute('role','group');pageNav.setAttribute('aria-label','Lecture pages');const studyTab=button('Study','page-tab',()=>setView('study',true)),examTab=button('Exam','page-tab',()=>setView('exam',true));pageNav.append(studyTab,examTab);
 const tools=el('div','toolbar');const theme=button('Dark mode','tool',()=>{const dark=root.classList.toggle('dark');theme.setAttribute('aria-pressed',dark);theme.textContent=dark?'Light mode':'Dark mode';state.dark=dark;save()});theme.setAttribute('aria-pressed',!!state.dark);if(state.dark){root.classList.add('dark');theme.textContent='Light mode'}
 const focus=button('Focus','tool',()=>{const on=root.classList.toggle('focus');focus.setAttribute('aria-pressed',on);focus.textContent=on?'Exit focus':'Focus'});focus.setAttribute('aria-pressed','false');tools.append(focus,theme,button('Print','tool',()=>window.print()));const line=el('div','progress-line');top.append(brand,pageNav,tools,line);
 const reader=el('div','reader'),side=el('aside','sidebar'),toc=el('nav','toc');toc.setAttribute('aria-label','Lecture chapters');side.append(el('div','overline','Your learning space'),el('div','side-course',d.course||'Lecture notes'),toc);
 const meter=el('div','study-meter'),row=el('div','meter-row'),percent=el('span','','0%');row.append(el('span','','Reading progress'),percent);const track=el('div','track'),fill=el('i');track.append(fill);meter.append(row,track,el('div','overline','Read. Connect. Remember.'));const template=el('a','download','Download JSON template ↗');template.href='medical-lecture.template.json?v=5.1.0';template.download='medical-lecture.template.json';meter.append(template);side.append(meter);
 const article=el('main','article');article.id='lecture-content';const hero=el('header','lecture-hero reveal-in');hero.append(el('div','overline',(d.course||'LECTURE')+' / '+(d.level||'Study guide')),el('h1','',d.title),el('p','dek',d.subtitle||'A focused space to understand, connect, and remember.'));
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 280 280');svg.classList.add('hero-art');svg.setAttribute('aria-hidden','true');for(let i=0;i<8;i++){const c=document.createElementNS(svg.namespaceURI,'circle');c.setAttribute('cx',140+Math.sin(i)*22);c.setAttribute('cy',140+Math.cos(i)*22);c.setAttribute('r',40+i*12);svg.append(c)}hero.append(svg);
 const meta=el('div','hero-meta');for(const text of [d.author||'Verdant collection',(d.durationMinutes||Math.max(3,Math.ceil(JSON.stringify(d).length/1200)))+' min read',d.blocks.filter(b=>b.type==='question').length+' recall prompts'])meta.append(el('span','',text));hero.append(meta);article.append(hero);
 const intro=el('div','intro-strip');intro.append(el('span','','A little structure. A deeper understanding.'),button('Begin lecture ↓','primary',()=>chapters[0]?.scrollIntoView({behavior:motion()})));article.append(intro);
	 const chapters=[],links=[];let section=null;const motion=()=>matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
	 const toRoman=value=>{const pairs=[[1000,'M'],[900,'CM'],[500,'D'],[400,'CD'],[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']];let number=value,result='';for(const [unit,glyph] of pairs)while(number>=unit){result+=glyph;number-=unit}return result};
	 const listMarker=(index,depth,rootHasChildren,itemCount)=>{if(depth===0)return rootHasChildren?(index+1)+'.':toRoman(index+1)+'.';if(itemCount===1)return '•';if(depth===1)return String.fromCharCode(65+index)+'.';if(depth===2)return toRoman(index+1)+'.';return (index+1)+'.'};
	 const renderNestedList=(items,style,depth=0,rootHasChildren=null)=>{if(rootHasChildren==null)rootHasChildren=items.some(item=>typeof item==='object'&&Array.isArray(item.children)&&item.children.length);const list=el('ol','content-list level-'+depth);list.setAttribute('role','list');items.forEach((raw,itemIndex)=>{const item=typeof raw==='string'?{text:raw}:raw,li=el('li','content-list-item'),row=el('div','content-list-row'),marker=listMarker(itemIndex,depth,rootHasChildren,items.length);row.append(el('span','content-list-marker',marker));const copy=el('div','content-list-copy');if(item.label)copy.append(el('span','content-list-label',item.label));copy.append(el('span','content-list-text',item.text));row.append(copy);li.append(row);if(item.children)li.append(renderNestedList(item.children,style,depth+1,rootHasChildren));list.append(li)});return list};
 const newChapter=title=>{const index=chapters.length,s=el('section','chapter');s.id='chapter-'+(index+1);const h=el('div','chapter-heading'),group=el('div');group.append(el('span','chapter-number','CHAPTER '+String(index+1).padStart(2,'0')),el('h2','',title));const saved=!!state['bookmark'+index];const mark=button(saved?'★':'☆','bookmark',()=>{state['bookmark'+index]=!state['bookmark'+index];mark.textContent=state['bookmark'+index]?'★':'☆';mark.setAttribute('aria-pressed',!!state['bookmark'+index]);save()});mark.setAttribute('aria-label','Bookmark '+title);mark.setAttribute('aria-pressed',saved);h.append(group,mark);s.append(h);article.append(s);chapters.push(s);const a=el('a');a.href='#'+s.id;a.append(el('span','toc-num',String(index+1).padStart(2,'0')),el('span','',title));a.onclick=e=>{e.preventDefault();s.scrollIntoView({behavior:motion()})};toc.append(a);links.push(a);return s;};
 for(const [index,b] of d.blocks.entries()){
 if(b.type==='section'||b.type==='title'){section=newChapter(b.title||b.text);if(b.description)section.append(el('p','',b.description));continue}
 if(!section)section=newChapter('The essentials');const block=el('div','block '+b.type+(b.variant==='lead'?' lead':''));
 if(b.type==='paragraph'||b.type==='subtitle'){if(b.heading)block.append(el('h3','',b.heading));block.append(el('p','',b.text))}
 if(['note','callout'].includes(b.type)){block.append(el('span','note-icon',b.type==='note'?'↗':'✦'));const text=el('div');text.append(el('div','label',b.label||b.title||'Key point'),el('p','',b.text));block.append(text)}
	 if(b.type==='objectives'||b.type==='references'){block.append(el('div','overline',b.title|| (b.type==='objectives'?'By the end of this lecture':'References')));const list=el('ul');for(const item of b.items)list.append(el('li','',item));block.append(list)}
	 if(b.type==='list'){const style=b.style||'bullets';block.classList.add('designed-list','list-'+style);const head=el('div','designed-list-head');head.append(el('div','overline',style==='numbered'||style==='steps'?'Ordered sequence':style==='key-points'?'High-yield points':'Structured notes'));if(b.title)head.append(el('h3','',b.title));if(b.description)head.append(el('p','',b.description));block.append(head,renderNestedList(b.items,style))}
 if(b.type==='flow'){block.classList.add('process');block.append(el('div','overline','Explore the sequence'),el('h3','',b.title||'Process'));const tabs=el('div','process-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label',b.title||'Process');const detail=el('div','step-detail');detail.id='process-'+index;detail.setAttribute('role','tabpanel');const items=b.steps.map(x=>typeof x==='string'?{title:x,description:''}:x),buttons=[];const select=i=>{buttons.forEach((btn,j)=>{btn.setAttribute('aria-selected',i===j);btn.tabIndex=i===j?0:-1});detail.setAttribute('aria-labelledby','step-'+index+'-'+i);detail.replaceChildren(el('strong','',items[i].title),el('p','',items[i].description||'Step '+(i+1)+' of '+items.length+' in this sequence.'))};items.forEach((x,i)=>{const btn=button(x.title,'',()=>select(i));btn.prepend(el('span','step-number',String(i+1).padStart(2,'0')));btn.id='step-'+index+'-'+i;btn.setAttribute('role','tab');btn.setAttribute('aria-controls',detail.id);btn.onkeydown=e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%items.length;else if(e.key==='ArrowLeft')n=(i-1+items.length)%items.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=items.length-1;else return;e.preventDefault();select(n);buttons[n].focus()};buttons.push(btn);tabs.append(btn)});block.append(tabs,detail);select(0)}
	 if(b.type==='table'){const purpose=b.purpose||'reference',purposeLabel={'quick-comparison':'Quick comparison','simplify-complexity':'Simplified system','rapid-review':'Rapid review','structured-variables':'Structured variables',reference:'Reference table'}[purpose],headGroup=el('div','table-block-head');headGroup.append(el('div','overline',purposeLabel));if(b.title)headGroup.append(el('h3','',b.title));if(b.description)headGroup.append(el('p','',b.description));block.append(headGroup);const wrap=el('div','table-wrap responsive-table'),table=el('table'),caption=el('caption','','');caption.textContent=b.title||purposeLabel;caption.hidden=true;table.setAttribute('role','table');table.append(caption);const head=el('thead'),hr=el('tr');head.setAttribute('role','rowgroup');hr.setAttribute('role','row');b.columns.forEach(x=>{const th=el('th','',x);th.scope='col';th.setAttribute('role','columnheader');hr.append(th)});head.append(hr);const body=el('tbody');body.setAttribute('role','rowgroup');b.rows.forEach(row=>{const tr=el('tr');tr.setAttribute('role','row');row.forEach((x,index)=>{const td=el('td','',x);td.setAttribute('role','cell');td.dataset.label=b.columns[index];tr.append(td)});body.append(tr)});table.append(head,body);wrap.append(table);block.append(wrap)}
 if(b.type==='image'){block.classList.add('lecture-image');const figure=el('figure'),frame=el('div','lecture-image-frame'),location=b.source.fileType==='pdf'?'PDF page '+b.source.page+(b.source.crop?' · crop '+b.source.crop.join(', '):''):b.source.fileType==='pptx'?'PPTX slide '+b.source.slide+' · '+(b.source.media||'image '+b.source.image):'DOCX · '+(b.source.media||'image '+b.source.image+' in document order');if(b.imageData){const image=el('img');image.src=b.imageData;image.alt=b.alt;image.loading='lazy';image.decoding='async';frame.append(image)}else{const placeholder=el('div','lecture-image-placeholder');placeholder.setAttribute('role','img');placeholder.setAttribute('aria-label','Image placeholder: '+b.alt);placeholder.append(el('span','lecture-image-icon','▧'),el('strong','',b.processName),el('small','',b.sourceLabel||location));frame.append(placeholder)}figure.append(frame);if(b.title||b.caption){const caption=el('figcaption');if(b.title)caption.append(el('strong','',b.title));if(b.caption)caption.append(el('span','',b.caption));figure.append(caption)}block.append(figure)}
 if(b.type==='question'){block.append(el('div','overline','Active recall / '+String(index+1).padStart(2,'0')),el('h3','',b.prompt));const answer=el('div','answer-panel');answer.id='answer-'+index;answer.hidden=true;answer.setAttribute('aria-live','polite');answer.textContent=b.answer;if(b.options){const options=el('div','quiz-options');b.options.forEach((text,i)=>{const btn=button(String.fromCharCode(65+i)+'  '+text,'quiz-option',()=>{options.querySelectorAll('button').forEach((n,j)=>{n.disabled=true;if(j===b.correctIndex)n.classList.add('correct')});if(i!==b.correctIndex)btn.classList.add('wrong');answer.textContent=(i===b.correctIndex?'Correct. ':'Review this concept. ')+b.answer;answer.hidden=false});options.append(btn)});block.append(options)}else{const reveal=button('Reveal explanation ↓','reveal',()=>{answer.hidden=!answer.hidden;reveal.setAttribute('aria-expanded',!answer.hidden);reveal.textContent=answer.hidden?'Reveal explanation ↓':'Hide explanation ↑'});reveal.setAttribute('aria-expanded','false');reveal.setAttribute('aria-controls',answer.id);block.append(reveal)}block.append(answer)}
 if(b.type==='checklist'){block.append(el('h3','',b.title||'Check your understanding'));const ul=el('ul');b.items.forEach((text,i)=>{const li=el('li'),label=el('label'),input=el('input');input.type='checkbox';input.checked=!!state['check'+index+'-'+i];input.onchange=()=>{state['check'+index+'-'+i]=input.checked;save()};label.append(input,el('span','',text));li.append(label);ul.append(li)});block.append(ul)}
 if(b.type==='step-process'||b.type==='tracked-step-process')block.append(renderStepProcess(b,'step-process-'+index));
 if(b.type==='structure-layers')block.append(renderStructureLayers(b,'structure-layers-'+index));
 if(b.type==='substance-journey')block.append(renderSubstanceJourney(b,'substance-journey-'+index));
 section.append(block);
 }
 const notes=el('section','block notes'),label=el('label','','Your margin notes'),area=el('textarea');area.id='lecture-notes';label.htmlFor=area.id;area.placeholder='What clicked? What would you like to revisit?';area.value=typeof state.notes==='string'?state.notes:'';const status=el('span','save-status','Notes stay in this browser.');status.setAttribute('aria-live','polite');area.oninput=()=>{state.notes=area.value;status.textContent=save()?'Saved in this browser.':'Storage unavailable. Copy your notes before leaving.'};notes.append(label,area,status);article.append(notes);
 const finish=el('div','finish'),message=el('div');message.append(el('div','overline','One idea at a time'),el('h3','','Make it stick.'),el('p','','Revisit the recall prompts. Explain the sequence in your own words.'));finish.append(message,button('Back to the beginning ↑','primary',()=>window.scrollTo({top:0,behavior:motion()})));article.append(finish);const footer=el('footer');footer.append(el('span','','VERDANT / LECTURE COLLECTION'),el('span','','Designed for deeper understanding'));article.append(footer);const examPage=renderExamPage(d);reader.append(side,article,examPage);const skip=el('a','skip-link','Skip to lecture');skip.href='#lecture-content';article.tabIndex=-1;root.append(skip,top,reader);document.body.append(root);window.installLectureSelection?.(article,root);
 const setView=(view,push=false)=>{view=view==='exam'?'exam':'study';const examOn=view==='exam';root.classList.toggle('exam-mode',examOn);article.hidden=examOn;examPage.hidden=!examOn;side.hidden=examOn;studyTab.setAttribute('aria-pressed',!examOn);examTab.setAttribute('aria-pressed',examOn);if(examOn){studyTab.removeAttribute('aria-current');examTab.setAttribute('aria-current','page')}else{studyTab.setAttribute('aria-current','page');examTab.removeAttribute('aria-current')}focus.hidden=examOn;if(examOn&&root.classList.contains('focus')){root.classList.remove('focus');focus.textContent='Focus';focus.setAttribute('aria-pressed','false')}skip.href=examOn?'#exam-content':'#lecture-content';skip.textContent=examOn?'Skip to exam':'Skip to lecture';if(push){const url=new URL(location.href);if(examOn)url.searchParams.set('view','exam');else url.searchParams.delete('view');history.pushState({lectureView:view},'',url)}window.scrollTo({top:0,behavior:'auto'});if(examOn)examPage.focus();else article.focus()};
 window.addEventListener('popstate',()=>setView(new URLSearchParams(location.search).get('view'),false));setView(new URLSearchParams(location.search).get('view'),false);
 const progress=()=>{const available=document.documentElement.scrollHeight-innerHeight;const p=available>0?Math.min(100,Math.max(0,Math.round(scrollY/available*100))):100;line.style.width=fill.style.width=p+'%';percent.textContent=p+'%';let current=0;chapters.forEach((s,i)=>{if(s.getBoundingClientRect().top<180)current=i});links.forEach((a,i)=>{a.classList.toggle('active',i===current);if(i===current)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})};let scheduled=false;window.addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(()=>{progress();scheduled=false})}},{passive:true});window.addEventListener('resize',progress);progress();
};
})();
